version: '3.8'

services:
  redis:
    image: 'redis:5-alpine'
    ports:
        - '6379:6379'
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        timeout: 20s
        retries: 10
  db:
    image: postgres:13-alpine
    env_file:
        - .env
    restart: always
    ports:
        - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 20s
        retries: 10
  api:
    build:
        context: ./
        dockerfile: dev.dockerfile
    env_file:
        - .env
    ports:
        - 8080:8080
    volumes:
        - ./:/app
    depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
