name: Build, Test, and Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Lint with go vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v -cover ./... -coverprofile coverage.out
        go tool cover -func coverage.out
